name: 'Publish new release'

on:
    pull_request:
        branches:
            - master
        types:
            - closed

jobs:
    release:
        name: Publish new release
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true # only merged pull requests must trigger this job
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - run: |
                  echo "CHANGES=`git log $(git describe --tags --abbrev=0)..HEAD --oneline`" >> $GITHUB_ENV

            - name: Extract version from branch name (for release branches)
              if: startsWith(github.event.pull_request.head.ref, 'release/')
              run: |
                  BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
                  VERSION=${BRANCH_NAME#release/}
                  echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
            - name: Extract version from branch name (for hotfix branches)
              if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
              run: |
                  BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
                  VERSION=${BRANCH_NAME#hotfix/}
                  echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

            - name: Create Release
              uses: thomaseizinger/create-release@1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
                  tag_name: ${{ env.RELEASE_VERSION }}
                  name: ${{ env.RELEASE_VERSION }}
                  draft: false
                  prerelease: false
                  body: ${{ env.CHANGES }}
            - name: Merge master into develop
              uses: thomaseizinger/create-pull-request@1.0.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  head: master
                  base: develop
                  title: Merge master into develop
                  body: |
                      This PR merges the master branch back into develop.
                      This happens to ensure that the updates that happend on the release branch before merging are written back to develop.

                      **This PR _must_ be merged!**

